
# docker-compose pour l'ensemble du projet MediLaboSolution
# pour l'instant on teste juste l'api-patient et son mysql
# + mongo et api_notes

services:
  db_sql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediLabPatients
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - patients_db:/var/lib/mysql
 
  db_mongo:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27018:27017"
    volumes:
      - notes_db:/data/db

  api_patients:
    build: ./api-patients
    container_name: api-patients
    ports:
      - "8091:8091"
    depends_on:
      - db_sql
    environment:
      SPRING_MYSQL_URL: jdbc:mysql://db_sql:3306
      SPRING_MYSQL_USERNAME: user
      SPRING_MYSQL_PASSWORD: password

  api_notes:
    build: ./api-notes
    container_name: api-notes
    ports:
      - "8092:8092"
    depends_on:
      - db_mongo

volumes:
  patients_db:
    external: true
  notes_db:
    external: true
