
# docker-compose pour l'ensemble du projet MediLaboSolution
# pour l'instant on teste juste l'api-patient et son mysql

version: '3.8'

services:
  db_sql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediLabPatients
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - patients_db:/var/lib/mysql

  api_patients:
    build: .
    container_name: api-patients
    ports:
      - "8091:8091"
    depends_on:
      - db_sql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_sql:3307
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  patients_db:
    external: true
  notes_db:
    external: true
