
# docker-compose pour l'ensemble du projet MediLaboSolution
# pour l'instant on teste juste l'api-patient et son mysql
# + mongo et api_notes

services:
  db_sql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediLabPatients
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - patients_db:/var/lib/mysql
 
  db_mongo:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: mediLabNotes
    ports:
      - "27018:27017"
    volumes:
      - notes_db:/data/db

  api_patients:
    build: ./api-patients
    container_name: api-patients
    ports:
      - "8091:8091"
    depends_on:
      - db_sql
    environment:
      SPRING_MYSQL_URL: jdbc:mysql://db_sql:3306
      SPRING_MYSQL_USERNAME: user
      SPRING_MYSQL_PASSWORD: password

  api_notes:
    build: ./api-notes
    container_name: api-notes
    ports:
      - "8092:8092"
    depends_on:
      - db_mongo
    environment:
      SPRING_MONGO_HOST: mongodb

  api_diabete:
    build: ./api-diabete
    container_name: api-diabete
    ports:
      - "8093:8093"
    environment:
      SPRING_MEDILAB_GATEWAY_URL: medilab-gateway:8090

  medilab_gateway:
    build: ./medilab-gateway
    container_name: medilab-gateway
    ports:
      - "8090:8090"
    environment:
      SPRING_MEDILAB_API_PATIENTS: http://api-patients:8091
      SPRING_MEDILAB_API_NOTES: http://api-notes:8092
      SPRING_MEDILAB_API_DIABETE: http://api-diabete:8093

  medilab_front:
    build: ./medilab-front
    container_name: medilab-front
    ports:
      - "8080:8080"
    environment:
      SPRING_MEDILAB_GATEWAY_URL: medilab-gateway:8090

volumes:
  patients_db:
    external: true
  notes_db:
    external: true
